import { boolean } from "https://deno.land/x/ts_matches@v5.4.1/mod.ts";
import { compat, types as T } from "../deps.ts";

export const getConfig: T.ExpectedExports.getConfig = compat.getConfig({
  "tor-address": {
    name: "Tor Address",
    description: "The Tor address for the main ui.",
    type: "pointer",
    subtype: "package",
    "package-id": "pushtx",
    target: "tor-address",
    interface: "main",
  },
  "lan-address": {
    name: "Lan Address",
    description: "The Lan address for the main ui.",
    type: "pointer",
    subtype: "package",
    "package-id": "pushtx",
    target: "lan-address",
    interface: "main",
  },
  bitcoind_rpcusername: {
    type: "pointer",
    name: "RPC Username",
    description: "The username for Bitcoin Core's RPC interface",
    subtype: "package",
    "package-id": "bitcoind",
    target: "config",
    multi: false,
    selector: "$.rpc.username",
  },
  bitcoind_rpcpassword: {
    type: "pointer",
    name: "RPC Password",
    description: "The password for Bitcoin Core's RPC interface",
    subtype: "package",
    "package-id": "bitcoind",
    target: "config",
    multi: false,
    selector: "$.rpc.password",
  },
  advanced: {
    type: "object",
    name: "Advanced settings",
    description: "Advanced settings",
    spec: {
      use_custom_node: {
        type: "boolean",
        name: "Use custom Bitcoin Node",
        description: "Use a custom bitcoin json-rpc server",
        default: false,
      },
      custom_rpchost: {
        type: "string",
        name: "Url",
        description: "Url of a Bitcoin json-rpc server",
        nullable: true,
        pattern: "http(s)?://.*",
        "pattern-description": "URL of a Bitcoin json-rpc server",
        copyable: true,
        placeholder: "http://hostname",
        default: "",
      },
      custom_rpcusername: {
        type: "string",
        name: "Username",
        description: "Username of custom Bitcoin json-rpc server",
        nullable: true,
        pattern: ".*",
        "pattern-description": "",
        copyable: true,
        placeholder: "bitcoin",
        default: "bitcoin",
      },
      custom_rpcpassword: {
        type: "string",
        name: "Password",
        description: "Password of custom Bitcoin json-rpc server",
        nullable: true,
        pattern: ".*",
        "pattern-description": "",
        copyable: true,
        placeholder: "",
        default: "",
        masked: true,
      },
    },
  },
});
